### ISSUE TITLE
轮到我写这个项目了···

### ISSUE THREAD

**Issue by RayHY** [chaoyan1037/text_editor_in_dos#2]
周纯杰的学生···
不知道学长最后得了多少分？这个项目怎么才能拿高分？支持代码高亮？

**Comment by HUSTyanchao** [comment]
哈哈，你是15级的学生吧。我得分也不高，好像是84分。。
  我当时做的功能比较简单，只是实现了简单的编辑功能，主要是要汉化，能够输入中文，还没考虑到用来写代码。。。
  C课设代码码多一点吧，代码量到一万行肯定能上90分了。。
 
Sender: KingSharp
Send Time: 2016-07-09 20:26
Receiver: HUSTyanchao/text_editor_in_dos
Subject: [HUSTyanchao/text_editor_in_dos] 轮到我写这个项目了··· (#2)
周纯杰的学生···
不知道学长最后得了多少分？这个项目怎么才能拿高分？支持代码高亮？
